"""Generate RELAY's software bill of materials from the installed packages themselves.

Walks the runtime requirements (the voice, percept and daily extras) transitively,
records each package's pinned version and the licence it declares in its own metadata,
and writes docs/SBOM.md plus packaging/requirements.lock. Licences a package does not
declare are filled from its upstream LICENSE file (listed below with the source), and
any copyleft licence is flagged so nobody has to rediscover it later.

    uv run python scripts/sbom.py
"""

from __future__ import annotations

import importlib.metadata as md
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNTIME_EXTRAS = ("voice", "percept", "daily")
# declared nowhere in the package metadata; checked against the upstream repository
UPSTREAM = {"pycaw": "MIT (upstream LICENSE, github.com/AndreMiras/pycaw)"}
COPYLEFT = re.compile(r"\b(A?GPL|LGPL)", re.I)


def _norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _licence(dist) -> str:
    m = dist.metadata
    name = _norm(m["Name"])
    if name in UPSTREAM:
        return UPSTREAM[name]
    expr = m.get("License-Expression")
    if expr:
        return expr
    cls = [c.split("::")[-1].strip() for c in (m.get_all("Classifier") or [])
           if c.startswith("License ::")]
    if cls:
        return ", ".join(cls)
    lic = (m.get("License") or "").strip()
    return lic.splitlines()[0][:60] if lic else "UNKNOWN"


def runtime_closure() -> dict:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    roots = []
    for extra in RUNTIME_EXTRAS:
        roots += data["project"]["optional-dependencies"].get(extra, [])
    seen: dict = {}
    todo = [re.split(r"[<>=!~ ;\[]", r, maxsplit=1)[0] for r in roots]
    while todo:
        name = _norm(todo.pop())
        if name in seen:
            continue
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            continue
        seen[name] = dist
        for req in dist.requires or []:
            if "extra ==" in req:
                continue
            if "sys_platform" in req and "win32" not in req and "!=" not in req:
                continue
            todo.append(re.split(r"[<>=!~ ;\[(]", req, maxsplit=1)[0])
    return seen


def main() -> int:
    deps = runtime_closure()
    rows = sorted((_norm(d.metadata["Name"]), d.version, _licence(d)) for d in deps.values())
    flagged = [r for r in rows if COPYLEFT.search(r[2]) or r[2] == "UNKNOWN"]
    lines = [
        "# RELAY — software bill of materials (runtime)",
        "",
        f"Generated by `scripts/sbom.py` from the installed packages' own metadata "
        f"(Python {sys.version.split()[0]}). {len(rows)} runtime packages. Build and test "
        "tools (pytest, ruff, PyInstaller) are not shipped and are not listed.",
        "",
        "| Package | Version | Licence |",
        "|---|---|---|",
    ] + [f"| {n} | {v} | {lic} |" for n, v, lic in rows] + [
        "",
        "## Copyleft or undeclared",
    ] + ([f"- **{n} {v}** — {lic}" for n, v, lic in flagged] or ["- none"]) + [""]
    (ROOT / "docs" / "SBOM.md").write_text("\n".join(lines), encoding="utf-8")
    pins = sorted(f"{d.metadata['Name']}=={d.version}" for d in deps.values())
    (ROOT / "packaging" / "requirements.lock").write_text(
        "# runtime pins generated by scripts/sbom.py\n" + "\n".join(pins) + "\n",
        encoding="utf-8")
    print(f"{len(rows)} runtime packages; flagged: {[f'{n} ({lic})' for n, _, lic in flagged]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
